dojo.provide("js.app.eventUtil");

js.app.eventUtil.formOMMRS = function() {
	dojo.connect(dijit.byId('btnSimpan'), "onClick", this, function() {
		var tanggal = dijit.byId('tanggal').get('value');
		var content = {
			tanggal		: dojo.date.locale.format(tanggal,{selector: 'date', datePattern: 'yyyy-MM-dd'}),
			pelanggan	: dijit.byId('pelanggan').get('value'),
			identifikasi: dijit.byId('identifikasi').get('value'),
			_1a : document.getElementById('_1aSel').value +" | "+ dijit.byId('_1aKet').get('value'),
			_1b : document.getElementById('_1bSel').value +" | "+ dijit.byId('_1bKet').get('value'),
			_1c : document.getElementById('_1cSel').value +" | "+ dijit.byId('_1cKet').get('value'),
			_1d : document.getElementById('_1dSel').value +" | "+ dijit.byId('_1dKet').get('value'),
			_2a : document.getElementById('_2aSel').value +" | "+ dijit.byId('_2aKet').get('value'),
			_2b : document.getElementById('_2bSel').value +" | "+ dijit.byId('_2bKet').get('value'),
			_2c : document.getElementById('_2cSel').value +" | "+ dijit.byId('_2cKet').get('value'),
			_2d : document.getElementById('_2dSel').value +" | "+ dijit.byId('_2dKet').get('value'),
			_2e : document.getElementById('_2eSel').value +" | "+ dijit.byId('_2eKet').get('value'),
			_2f : document.getElementById('_2fSel').value +" | "+ dijit.byId('_2fKet').get('value'),
			_3a : document.getElementById('_3aSel').value +" | "+ dijit.byId('_3aKet1').get('value') +" | "+ dijit.byId('_3aKet2').get('value') +" | "+ dijit.byId('_3aKet3').get('value'),
			_3b : document.getElementById('_3bSel').value +" | "+ dijit.byId('_3bKet1').get('value') +" | "+ dijit.byId('_3bKet2').get('value') +" | "+ dijit.byId('_3bKet3').get('value'),
			_3c : document.getElementById('_3cSel').value +" | "+ dijit.byId('_3cKet1').get('value') +" | "+ dijit.byId('_3cKet2').get('value') +" | "+ dijit.byId('_3cKet3').get('value'),
			_3d : document.getElementById('_3dSel').value +" | "+ dijit.byId('_3dKet1').get('value') +" | "+ dijit.byId('_3dKet2').get('value') +" | "+ dijit.byId('_3dKet3').get('value'),
			_3e : document.getElementById('_3eSel').value +" | "+ dijit.byId('_3eKet1').get('value') +" | "+ dijit.byId('_3eKet2').get('value') +" | "+ dijit.byId('_3eKet3').get('value'),
			_3f : document.getElementById('_3fSel').value +" | "+ dijit.byId('_3fKet1').get('value') +" | "+ dijit.byId('_3fKet2').get('value') +" | "+ dijit.byId('_3fKet3').get('value'),
			_3g : document.getElementById('_3gSel').value +" | "+ dijit.byId('_3gKet1').get('value') +" | "+ dijit.byId('_3gKet2').get('value') +" | "+ dijit.byId('_3gKet3').get('value'),
			_3h : document.getElementById('_3hSel').value +" | "+ dijit.byId('_3hKet1').get('value') +" | "+ dijit.byId('_3hKet2').get('value') +" | "+ dijit.byId('_3hKet3').get('value'),
			_3i : document.getElementById('_3iSel').value +" | "+ dijit.byId('_3iKet').get('value'),
			_3j : document.getElementById('_3jSel').value +" | "+ dijit.byId('_3jKet').get('value'),
			_3k : document.getElementById('_3kSel').value +" | "+ dijit.byId('_3kKet1').get('value') +" | "+ dijit.byId('_3kKet2').get('value'),
			_3l : document.getElementById('_3lSel').value +" | "+ dijit.byId('_3lKet1').get('value') +" | "+ dijit.byId('_3lKet2').get('value'),
			_3m : document.getElementById('_3mSel').value +" | "+ dijit.byId('_3mKet1').get('value') +" | "+ dijit.byId('_3mKet2').get('value'),
			_3n : document.getElementById('_3nSel').value +" | "+ dijit.byId('_3nKet1').get('value') +" | "+ dijit.byId('_3nKet2').get('value'),
			_3o : document.getElementById('_3oSel').value +" | "+ dijit.byId('_3oKet1').get('value') +" | "+ dijit.byId('_3oKet2').get('value'),
			_3p : document.getElementById('_3pSel').value +" | "+ dijit.byId('_3pKet').get('value'),
			_3q : document.getElementById('_3qSel').value +" | "+ dijit.byId('_3qKet').get('value'),
			_3r : document.getElementById('_3rSel').value +" | "+ dijit.byId('_3rKet').get('value'),
			_3s : document.getElementById('_3sSel').value +" | "+ dijit.byId('_3sKet').get('value'),
			_3t : document.getElementById('_3tSel').value +" | "+ dijit.byId('_3tKet').get('value'),
			_4a : document.getElementById('_4aSel').value +" | "+ dijit.byId('_4aKet').get('value'),
			_4b : document.getElementById('_4bSel').value +" | "+ dijit.byId('_4bKet').get('value'),
			_4c : document.getElementById('_4cSel').value +" | "+ dijit.byId('_4cKet').get('value'),
			_4d : document.getElementById('_4dSel').value +" | "+ dijit.byId('_4dKet').get('value'),
			_4e : document.getElementById('_4eSel').value +" | "+ dijit.byId('_4eKet').get('value'),
			_5a : document.getElementById('_5aSel').value +" | "+ dijit.byId('_5aKet').get('value'),
			_5b : document.getElementById('_5bSel').value +" | "+ dijit.byId('_5bKet').get('value'),
			_5c : document.getElementById('_5cSel').value +" | "+ dijit.byId('_5cKet').get('value'),
			_5d : document.getElementById('_5dSel').value +" | "+ dijit.byId('_5dKet').get('value'),
			_6a : document.getElementById('_6aSel').value,
			_6b : document.getElementById('_6bSel').value,
			_6c : document.getElementById('_6cSel').value +" | "+ dijit.byId('_6cKet').get('value'),
			_6d : document.getElementById('_6dSel').value +" | "+ dijit.byId('_6dKet1').get('value') +" | "+ dijit.byId('_6dKet2').get('value'),
			_6e : document.getElementById('_6eSel').value +" | "+ document.getElementById('_6eSel2').value +" | "+ dijit.byId('_6eKet1').get('value') +" | "+ dijit.byId('_6eKet2').get('value') +" | "+ dijit.byId('_6eKet3').get('value'),
			_6f : dijit.byId('_6fKet1').get('value') +" | "+ dijit.byId('_6fKet2').get('value') +" | "+ dijit.byId('_6fKet3').get('value') +" | "+ dijit.byId('_6fKet4').get('value'),
			_6g : dijit.byId('_6gKet').get('value'),
			_6h : document.getElementById('_6hSel').value +" | "+ dijit.byId('_6hKet').get('value'),
			_6i : dijit.byId('_6iKet1').get('value') +" | "+ dijit.byId('_6iKet2').get('value'),
			_7a : document.getElementById('_7aSel').value +" | "+ dijit.byId('_7aKet').get('value'),
			_7b : document.getElementById('_7bSel').value +" | "+ dijit.byId('_7bKet').get('value'),
			_7c : document.getElementById('_7cSel').value +" | "+ dijit.byId('_7cKet').get('value'),
			_7d : document.getElementById('_7dSel').value +" | "+ dijit.byId('_7dKet').get('value'),
			_7e : document.getElementById('_7eSel').value +" | "+ dijit.byId('_7eKet').get('value'),
			_8a : document.getElementById('_8aSel').value +" | "+ dijit.byId('_8aKet').get('value'),
			_8b : document.getElementById('_8bSel').value +" | "+ dijit.byId('_8bKet').get('value'),
			_8c : document.getElementById('_8cSel').value +" | "+ dijit.byId('_8cKet').get('value'),
			_8d : document.getElementById('_8dSel').value +" | "+ dijit.byId('_8dKet').get('value'),
			_9a : document.getElementById('_9aSel').value +" | "+ dijit.byId('_9aKet').get('value'),
			_9b : document.getElementById('_9bSel').value +" | "+ dijit.byId('_9bKet').get('value'),
			_9c : document.getElementById('_9cSel').value +" | "+ dijit.byId('_9cKet').get('value'),
			_10a : document.getElementById('_10aSel').value +" | "+ dijit.byId('_10aKet').get('value'),
			_10b : document.getElementById('_10bSel').value +" | "+ dijit.byId('_10bKet').get('value'),
			_10c : document.getElementById('_10cSel').value +" | "+ dijit.byId('_10cKet').get('value'),
			_10d : document.getElementById('_10dSel').value +" | "+ dijit.byId('_10dKet').get('value'),
			_10e : document.getElementById('_10eSel').value +" | "+ dijit.byId('_10eKet').get('value'),
			_11a : document.getElementById('_11aSel').value +" | "+ dijit.byId('_11aKet').get('value'),
			_11b : document.getElementById('_11bSel').value +" | "+ dijit.byId('_11bKet').get('value'),
			_11c : document.getElementById('_11cSel').value +" | "+ dijit.byId('_11cKet').get('value'),
			_12a : document.getElementById('_12aSel').value +" | "+ dijit.byId('_12aKet').get('value'),
			_13a : document.getElementById('_13aSel').value +" | "+ dijit.byId('_13aKet').get('value'),
			_14a : document.getElementById('_14aSel').value +" | "+ dijit.byId('_14aKet').get('value'),
			_14b : document.getElementById('_14bSel').value +" | "+ dijit.byId('_14bKet').get('value'),
			_14c : document.getElementById('_14cSel').value +" | "+ dijit.byId('_14cKet').get('value'),
			_14d : document.getElementById('_14dSel').value +" | "+ dijit.byId('_14dKet').get('value'),
			_14e : document.getElementById('_14eSel').value +" | "+ dijit.byId('_14eKet1').get('value') +" | "+ dijit.byId('_14eKet2').get('value') +" | "+ dijit.byId('_14eKet3').get('value') +" | "+ dijit.byId('_14eKet4').get('value'),
			_14f : document.getElementById('_14fSel').value +" | "+ dijit.byId('_14fKet1').get('value') +" | "+ dijit.byId('_14fKet2').get('value') +" | "+ dijit.byId('_14fKet3').get('value'),
			_15a : document.getElementById('_15aSel').value +" | "+ dijit.byId('_15aKet').get('value'),
			_15b : document.getElementById('_15bSel').value +" | "+ dijit.byId('_15bKet').get('value'),
			_15c : document.getElementById('_15cSel').value +" | "+ dijit.byId('_15cKet').get('value'),
			_15d : document.getElementById('_15dSel').value +" | "+ dijit.byId('_15dKet').get('value'),
			_15e : document.getElementById('_15eSel').value +" | "+ dijit.byId('_15eKet').get('value')
		}; 

		dojo.xhrPost({
			url: 'system/simpan.php',
			content: content,
			load: function(data) {
				alert('berhasil');
			}
		});
	});
}


